[tools]
rojo = "rojo-rbx/rojo@7.4.1"
lune = "filiptibell/lune@0.8.0"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.26.1"
stylua = "JohnnyMorganz/stylua@0.20.0"
darklua = "seaofvoices/darklua@0.12.1"
