[tools]
rojo = "rojo-rbx/rojo@7.4.4"
lune = "filiptibell/lune@0.8.9"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.27.1"
stylua = "JohnnyMorganz/stylua@0.20.0"
darklua = "seaofvoices/darklua@0.13.1"
