name = "std"
description = "Runtime agnostic access to standard libraries"
version = "1.0.2"

types = ["Runtime", "RuntimeDefinition", "TaskLib"]

targets = ["lune", "roblox"]

[engines]
pesde = "^0.7.1"
lune = "=0.10.2"