name = "future"
description = "Future<T> type in Luau"
version = "1.0.2"

types = ["Future<T>"]
dependencies = ["option", "threadpool", "std"]

targets = ["lune", "roblox"]

[engines]
pesde = "^0.7.1"
lune = "=0.10.2"
