name = "timer"
description = "Schedule functions to be called at a future time."
version = "1.0.2"

dependencies = ["std", "future", "threadpool"]

targets = ["lune", "roblox"]

[engines]
pesde = "^0.7.1"
lune = "=0.10.2"