name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true
      - run: lune run build
      - run: lune run test
      - run: mise exec github:lune-org/lune@0.8.9 -- lune run test
      - run: stylua --check .
